opensearch-project/opensearch-metrics

.github/workflows/cdk-ci-test.yml
.github/workflows/java-ci-test.yml

On board Code Coverage

---

.codecov.yml
README.md
src/main/java/org/opensearchmetrics/util/OpenSearchUtil.java

Add .codecov.yml and code cleanup

Add .codecov.yml and code cleanup

---

infrastructure/package-lock.json
infrastructure/package.json
src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java

Update the release inputs with release versions

Update the release inputs with release versions

---

infrastructure/lib/stacks/opensearchNginxProxyReadonly.ts
infrastructure/test/nginx.test.ts

Nginx conf update and update the resource properties
Fix the error ` ERRO[86682]`.

Nginx conf update and update the resource properties

---

infrastructure/lib/stacks/monitoringDashboard.ts
infrastructure/lib/stacks/opensearch.ts
infrastructure/lib/stacks/opensearchNginxProxyReadonly.ts
infrastructure/package-lock.json
infrastructure/package.json
infrastructure/test/monitoring-stack.test.ts
infrastructure/test/opensearch-stack.test.ts

1. Cluster Upgrade to 2.13
2. Nginx conf update.
3. Cluster master change instance type.
4. Change alarm Schedule.rate to every 15 mins.
5. CDK package upgrade to `2.146.0`.

Project Metrics Infrastructure Improvements 

---

README.md

Update the project readme with new metrics added.
Part of https://github.com/opensearch-project/opensearch-metrics/issues/56

Update the project readme with new metrics added.

---

infrastructure/lib/stacks/metricsWorkflow.ts
src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java

Update release inputs and workflow run cron schedule

Update release inputs and workflow run cron schedule

---

src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java

Changed the 1.3.19 version from open to closed.

Changed 1.3.19 to closed

---

src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java

In ReleaseInputs, changed 2.17 to closed.
Part of https://github.com/opensearch-project/opensearch-build/issues/4908 

Changed 2.17 to closed

---

src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java

Onboard 2.18.0 release
Part of https://github.com/opensearch-project/opensearch-build/issues/5004

Onboard 2.18.0 release

---

README.md

Update the README to include detailed flow information for monitoring critical GitHub workflows
Part of https://github.com/opensearch-project/opensearch-build/issues/4941

Update the README to include detailed flow information for monitoring critical GitHub workflows

---

infrastructure/lib/stacks/gitHubAutomationApp.ts

Changed automation app branch to 0.1.10

Changed automation app branch to 0.1.10

---

infrastructure/lib/stacks/gitHubAutomationApp.ts

Bump automation app to 0.1.13

---

infrastructure/lib/stacks/gitHubAutomationApp.ts

Remove automation-app branch until mechanism in place to update

Remove automation-app branch until mechanism in place to update

---

src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java

Close the 2.18.0 release
https://github.com/opensearch-project/opensearch-build/issues/5004

Close the 2.18.0 release

---

src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java

Track 1.3.20 in release inputs
Part of https://github.com/opensearch-project/opensearch-build/issues/4990

Track 1.3.20 in release inputs

---

src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java

Onboard 2.19.0 Release.
Part of https://github.com/opensearch-project/opensearch-build/issues/5152

Onboard 2.19.0 Release

---

src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java

Added 2.19.1 to release inputs
Part of https://github.com/opensearch-project/opensearch-build/issues/5323

Added 2.19.1 to release inputs

---

src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java

Closing 2.19.1 since its out. 

Close 2.19.1 release

---

src/main/java/org/opensearchmetrics/metrics/release/ReleaseIssueChecker.java

Filter release issues and release owners for open issues only
resolves https://github.com/opensearch-project/opensearch-metrics/issues/123

Filter release issues and release owners for open issues only

---

src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java

Update the release inputs to stop tracking old releases
Part of https://github.com/opensearch-project/opensearch-build/pull/5434

Update the release inputs to stop tracking old releases

---

src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java

Add Release 2.19.2 to release input

Add Release 2.19.2 to release input

---

src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java

- Add 3.1.0 release
- Fix branch for 3.0 release
- Closes 2.19.2 release as it is out
- Stops tracking of 2.18.0
https://github.com/opensearch-project/opensearch-build/issues/5487

Add 3.1.0 and fix branch for 3.0 release

---

src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java

Move 3.1. to closed in release inputs
