opensearch-project/opensearch-metrics

- README.md
Update the README with newly added Gradle Check Metrics.
Coming from https://github.com/opensearch-project/OpenSearch/issues/11217#issuecomment-2140815607.
> Update the README with newly added Gradle Check Metrics

- infrastructure/canary/nodejs/node_modules/urlMonitor.js
- infrastructure/test/monitoring-stack.test.ts
Added click tests to the Canary script that tests if OpenSearch Dashboards is accessible to test the UI and make sure the dashboard is working.
> Added click UI tests to Canary URL monitoring

- infrastructure/lib/constructs/canarySns.ts
- infrastructure/package-lock.json
- infrastructure/test/monitoring-stack.test.ts
Canary fails once every so often due to UI loading times. Lowering the threshold will prevent these failures from changing alarm state.
> Changed Canary alarm threshold from 100 to 50

- src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
- src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java
Reverted adding 1.3.18 to ReleaseInputs
> Reverted adding 1.3.18 to ReleaseInputs

- infrastructure/canary/nodejs/node_modules/urlMonitor.js
- infrastructure/lib/constructs/canarySns.ts
- infrastructure/lib/constructs/lambda.ts
- infrastructure/lib/constructs/opensearchCognito.ts
- infrastructure/lib/constructs/opensearchNginxProxyCognito.ts
- infrastructure/lib/constructs/snsMonitor.ts
- infrastructure/lib/constructs/stepFunctionSns.ts
- infrastructure/lib/enums/project.ts
- infrastructure/lib/infrastructure-stack.ts
- infrastructure/lib/stacks/metricsWorkflow.ts
- infrastructure/lib/stacks/monitoringDashboard.ts
- infrastructure/lib/stacks/opensearch.ts
- infrastructure/lib/stacks/opensearchNginxProxyReadonly.ts
- infrastructure/lib/stacks/route53.ts
- infrastructure/lib/stacks/secrets.ts
- infrastructure/lib/stacks/vpc.ts
- infrastructure/lib/stacks/waf.ts
- infrastructure/package-lock.json
- infrastructure/package.json
- infrastructure/test/hostedzone-stack.test.ts
- infrastructure/test/monitoring-stack.test.ts
- infrastructure/test/nginx.test.ts
- infrastructure/test/opensearch-stack.test.ts
- infrastructure/test/secrets-stack.test.ts
- infrastructure/test/vpc-stack.test.ts
- infrastructure/test/workflow-stack.test.ts
* Upgrade typescript to `^4.6.3`
* Adds the missing license to infrastructure code
* Formats the code
* Removes unused and wildcard imports
* Rearranges the imports
IDE used: vscode
part of https://github.com/opensearch-project/opensearch-metrics/issues/55
> Upgrade typescript, format the code and add license header

- src/main/java/org/opensearchmetrics/dagger/MetricsModule.java
- src/main/java/org/opensearchmetrics/metrics/MetricsCalculation.java
- src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
- src/main/java/org/opensearchmetrics/metrics/release/ReleaseIssueChecker.java
- src/main/java/org/opensearchmetrics/metrics/release/ReleaseMetrics.java
- src/main/java/org/opensearchmetrics/model/release/ReleaseMetricsData.java
- src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java
- src/test/java/org/opensearchmetrics/metrics/release/ReleaseIssueCheckerTest.java
- src/test/java/org/opensearchmetrics/metrics/release/ReleaseMetricsTest.java
- src/test/java/org/opensearchmetrics/model/release/ReleaseMetricsDataTest.java
Update release metrics to include the component level release issue and owner details.
Sample source document 
```
"_source": {
"release_notes": true,
"version_increment": true,
"release_issue": "https://github.com/opensearch-project/notifications/issues/782",
"autocut_issues_open": 0,
"repository": "notifications",
"release_state": "closed",
"version": "2.12.0",
"pulls_open": 0,
"current_date": "2024-08-20T18:59:43.223873761",
"release_branch": true,
"issues_closed": 9,
"pulls_closed": 10,
"id": "4bf8c249-9455-3706-9704-fe71adfe5e34",
"issues_open": 0,
"release_version": "2.12.0",
"release_owners": [
"praveensameneni",
"sbcd90"
]
},
``` 
Part of https://github.com/opensearch-project/opensearch-metrics/issues/61 and https://github.com/opensearch-project/opensearch-metrics/issues/51
By …
> Update release metrics to include the component level release issue and owner details

- src/main/java/org/opensearchmetrics/metrics/MetricsCalculation.java
- src/main/java/org/opensearchmetrics/metrics/release/ReleaseMetrics.java
- src/main/java/org/opensearchmetrics/metrics/release/ReleaseRepoFetcher.java
- src/main/java/org/opensearchmetrics/model/release/ReleaseMetricsData.java
- src/test/java/org/opensearchmetrics/metrics/MetricsCalculationTest.java
- src/test/java/org/opensearchmetrics/metrics/release/ReleaseMetricsTest.java
- src/test/java/org/opensearchmetrics/metrics/release/ReleaseRepoFetcherTest.java
- src/test/java/org/opensearchmetrics/model/release/ReleaseMetricsDataTest.java
Support component name for release metrics. This should be able to help user filter the documents with repo name or component name. In the following example find the result either by `anomaly-detection-dashboards-plugin` or by `anomalyDetectionDashboards` should yield the same results.
```
"_source": {
"release_issue_exists": true,
"release_notes": false,
"version_increment": true,
"release_issue": "https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/802",
"autocut_issues_open": 0,
"repository": "anomaly-detection-dashboards-plugin",
"release_state": "closed",
"version": "2.15.0",
"pulls_open": 0,
"release_owner_exists": false,
"current_date": "2024-08-26T21:25:20.901042281",
"component": "anomalyDetectionDashboards",
"release_branch": true,
"issues_closed": …
```
> Support component name filter for release metrics

- infrastructure/lib/stacks/opensearchNginxProxyReadonly.ts
Support central of the metrics in the https://opensearch.org/. The solution is based on this comment https://github.com/opensearch-project/opensearch-metrics/issues/69#issuecomment-2322060961.
This PR should allow the Iframe embedding on for https://opensearch.org and DENY by default.
Part of https://github.com/opensearch-project/opensearch-metrics/issues/69 and https://github.com/opensearch-project/opensearch-metrics/issues/51
> Support central of the metrics

- DEVELOPER_GUIDE.md
- infrastructure/lib/infrastructure-stack.ts
- infrastructure/lib/stacks/gitHubAutomationApp.ts
- infrastructure/test/gitHubAutomationApp-stack.test.ts
Resources to launch GitHub Automation App
- This PR needs to be merged https://github.com/opensearch-project/automation-app/pull/12 1st.
- After the above PR is merged, the new CDK stacks will create a GitHub app secret (update the secret value) and resources to launch the GitHub app.
- Ec2 autoscaling group with right launch configuration to run the app.
- Permissions to the Ec2 role to fetch the GitHub app secret and list to the GitHub events.
- Runs 2 docker containers to support [github-merged-pulls-monitor](https://github.com/opensearch-project/automation-app/blob/main/src/call/github-merged-pulls-monitor.ts) and [github-workflow-runs-monitor](https://github.com/opensearch-project/automation-app/blob/main/src/call/github-workflow-runs-monitor.ts).
- Permissions to index the data to …
> Resources to launch GitHub Automation App

- infrastructure/lib/infrastructure-stack.ts
- infrastructure/lib/stacks/opensearch.ts
- infrastructure/test/opensearch-stack.test.ts
Update the cluster access policy with GitHub automation app access role.
Part of https://github.com/opensearch-project/opensearch-build/issues/4941 
> Update the cluster access policy with GitHub automation app access role

- DEVELOPER_GUIDE.md
- infrastructure/lib/infrastructure-stack.ts
- infrastructure/lib/stacks/gitHubAutomationApp.ts
- infrastructure/lib/stacks/gitHubWorkflowMonitorAlarms.ts
- infrastructure/test/gitHubAutomationApp-stack.test.ts
- infrastructure/test/githubWorkflowMonitorAlarms-stack.test.ts
Github Automation App to monitor the critical workflows:
- Creates the Alarms for each critical workflow.
- Creates the Alarms for each critical workflow with restrictive metric and namespace.
- The app logic during runtime and based on the workflow result will update the workflow specific alarm metrics, related PR https://github.com/opensearch-project/automation-app/pull/21.
- The GitHub App role will have restrictive access to publish the alarm metrics.
Part of https://github.com/opensearch-project/opensearch-build/issues/4941
For more information on following Developer Certificate of Origin and signing off your commits, please check …
> Github Automation App to monitor the critical workflows

- DEVELOPER_GUIDE.md
- infrastructure/lib/infrastructure-stack.ts
- infrastructure/lib/stacks/gitHubAutomationApp.ts
- infrastructure/lib/stacks/s3.ts
- infrastructure/lib/stacks/vpc.ts
- infrastructure/test/gitHubAutomationApp-stack.test.ts
- infrastructure/test/s3-stack.test.ts
Coming from https://github.com/opensearch-project/opensearch-metrics/issues/76
1. Added an S3 bucket
2. Added the automation app docker container to upload github events to s3
3. Added role for ec2 to write to s3.
> Added functionality to store github events in s3 bucket

- infrastructure/lib/stacks/gitHubAutomationApp.ts
Coming from https://github.com/opensearch-project/automation-app/pull/27
Upgrade the automation app version to fix event name bug.
> Bump automation app to 0.1.12

- DEVELOPER_GUIDE.md
- build.gradle
- infrastructure/lib/infrastructure-stack.ts
- infrastructure/lib/stacks/metricsWorkflow.ts
- infrastructure/lib/stacks/monitoringDashboard.ts
- infrastructure/lib/stacks/opensearch.ts
- infrastructure/lib/stacks/s3EventIndexWorkflow.ts
- infrastructure/test/metrics-workflow-stack.test.ts
- infrastructure/test/monitoring-stack.test.ts
- infrastructure/test/nginx.test.ts
- infrastructure/test/opensearch-stack.test.ts
- infrastructure/test/s3-event-index-workflow-stack.test.ts
- src/main/java/org/opensearchmetrics/dagger/CommonModule.java
- src/main/java/org/opensearchmetrics/dagger/ServiceComponent.java
- src/main/java/org/opensearchmetrics/lambda/GithubEventsLambda.java
- src/main/java/org/opensearchmetrics/metrics/events/GithubEvents.java
- src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
- src/main/java/org/opensearchmetrics/model/event/EventData.java
- src/main/java/org/opensearchmetrics/util/S3Util.java
- src/test/java/org/opensearchmetrics/lambda/GithubEventsLambdaTest.java
- src/test/java/org/opensearchmetrics/metrics/events/GithubEventsTest.java
- src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java
- src/test/java/org/opensearchmetrics/model/event/EventDataTest.java
- src/test/java/org/opensearchmetrics/util/S3UtilTest.java
Added lambda to index events from s3 data lake to metrics cluster
> Added workflow to index events from s3 data lake to metrics cluster

- infrastructure/lib/stacks/s3EventIndexWorkflow.ts
- infrastructure/test/s3-event-index-workflow-stack.test.ts
The EventBridge Rule was passing matching input to the s3 event index lambda causing errors. The s3 event index lambda requires an input of `{}` to default to yesterday, so this change adds this input to the EventBridge Rule.
> Fix to add manual default input to eventbridge rule

- .github/workflows/cdk-ci-test.yml
- build.gradle
- src/main/java/org/opensearchmetrics/dagger/MetricsModule.java
- src/main/java/org/opensearchmetrics/lambda/MetricsLambda.java
- src/main/java/org/opensearchmetrics/metrics/MetricsCalculation.java
- src/main/java/org/opensearchmetrics/metrics/release/CodeCoverage.java
- src/main/java/org/opensearchmetrics/metrics/release/ReleaseMetrics.java
- src/main/java/org/opensearchmetrics/metrics/release/ReleaseVersionIncrementChecker.java
- src/main/java/org/opensearchmetrics/model/codecov/CodeCovResponse.java
- src/main/java/org/opensearchmetrics/model/codecov/CodeCovResult.java
- src/main/java/org/opensearchmetrics/model/release/ReleaseMetricsData.java
- src/test/java/org/opensearchmetrics/lambda/MetricsLambdaTest.java
- src/test/java/org/opensearchmetrics/metrics/MetricsCalculationTest.java
- src/test/java/org/opensearchmetrics/metrics/release/CodeCoverageTest.java
- src/test/java/org/opensearchmetrics/metrics/release/ReleaseMetricsTest.java
- src/test/java/org/opensearchmetrics/metrics/release/ReleaseVersionIncrementCheckerTest.java
- src/test/java/org/opensearchmetrics/model/codecov/CodeCovDoubleSerializerTest.java
- src/test/java/org/opensearchmetrics/model/codecov/CodeCovResponseTest.java
- src/test/java/org/opensearchmetrics/model/codecov/CodeCovResultTest.java
Onboard repo code coverage metrics and mechanism to link with existing release metrics.
```
"_source": {
"coverage": 43.41,
"current_date": "2024-10-28T17:54:41.742113549",
"component": "customImportMapDashboards",
"id": "b10b960e-b31f-3cb1-9a55-5e87ed2ade6b",
"commitid": "511840ae5ca900610d521aad311677445269055f",
"state": "complete",
"repository": "dashboards-maps",
"release_version": "2.18.0",
"release_state": "open",
"version": "2.18.0",
"branch": "2.18",
"url": "https://api.codecov.io/api/v2/github/opensearch-project/repos/dashboards-maps/commits?branch=2.18"
},
```
```
"_source": {
"coverage": 0,
"current_date": "2024-10-28T17:54:41.742113549",
"component": "OpenSearch",
"id": "09c026db-49b3-3502-ae80-717c6db4b8e1",
"commitid": "none",
"state": "no-coverage",
"repository": …
```
> Onboard repo code coverage metrics

- DEVELOPER_GUIDE.md
- infrastructure/lib/infrastructure-stack.ts
- infrastructure/lib/stacks/maintainerInactivityWorkflow.ts
- infrastructure/lib/stacks/monitoringDashboard.ts
- infrastructure/test/maintainer-inactivity-workflow-stack.test.ts
- infrastructure/test/monitoring-stack.test.ts
- src/main/java/org/opensearchmetrics/dagger/CommonModule.java
- src/main/java/org/opensearchmetrics/lambda/MaintainerInactivityLambda.java
- src/main/java/org/opensearchmetrics/metrics/MetricsCalculation.java
- src/main/java/org/opensearchmetrics/metrics/maintainer/MaintainerMetrics.java
- src/main/java/org/opensearchmetrics/model/maintainer/LatestEventData.java
- src/main/java/org/opensearchmetrics/model/maintainer/MaintainerData.java
- src/test/java/org/opensearchmetrics/lambda/GithubEventsLambdaTest.java
- src/test/java/org/opensearchmetrics/lambda/MaintainerInactivityLambdaTest.java
- src/test/java/org/opensearchmetrics/lambda/SlackLambdaTest.java
- src/test/java/org/opensearchmetrics/metrics/MetricsCalculationTest.java
- src/test/java/org/opensearchmetrics/metrics/maintainer/MaintainerMetricsTest.java
- src/test/java/org/opensearchmetrics/model/maintainer/LatestEventDataTest.java
- src/test/java/org/opensearchmetrics/model/maintainer/MaintainerDataTest.java
Reindexed GitHub Events stored in the metrics cluster into maintainer inactivity data for further display.
> Reindex GitHub Events into maintainer inactivity data

- src/main/java/org/opensearchmetrics/metrics/maintainer/MaintainerMetrics.java
- src/test/java/org/opensearchmetrics/metrics/maintainer/MaintainerMetricsTest.java
Fixed a bug with not having null checks for queried event fields.
Part of https://github.com/opensearch-project/opensearch-metrics/issues/75
> Added null checks for queried event fields

- src/main/java/org/opensearchmetrics/metrics/maintainer/MaintainerMetrics.java
- src/test/java/org/opensearchmetrics/metrics/maintainer/MaintainerMetricsTest.java
Add unique github id check when scraping MAINTAINERS.md file in case of duplicate github ids.
Part of https://github.com/opensearch-project/opensearch-metrics/issues/75
> Add unique github id check

- infrastructure/lib/constructs/opensearchNginxProxyCognito.ts
- infrastructure/lib/stacks/opensearchNginxProxyReadonly.ts
Coming from https://futurestud.io/tutorials/nginx-how-to-fix-ssl-directive-is-deprecated-use-listen-ssl
Part of https://github.com/opensearch-project/opensearch-metrics/issues/51
> Update ssl setting to support nginx/1.26.2

- infrastructure/lib/stacks/gitHubAutomationApp.ts
Lock automation app version to 0.1.18 and change resource config for automation app.
> Lock version and change resource config for automation app

- infrastructure/lib/stacks/maintainerInactivityWorkflow.ts
- infrastructure/lib/stacks/s3EventIndexWorkflow.ts
- infrastructure/test/maintainer-inactivity-workflow-stack.test.ts
- infrastructure/test/s3-event-index-workflow-stack.test.ts
Changed maintainer dashboard lambda to run at the start of UTC day
> Changed maintainer dashboard lambda to run at the start of UTC day

- src/main/java/org/opensearchmetrics/metrics/maintainer/MaintainerMetrics.java
Fixing a bug in the Maintainer Dashboard where events are not found when the username in `MAINTAINER.md` and GitHub differ in case.
> Changed latest event sender query from keyword field to text field

- src/main/java/org/opensearchmetrics/lambda/GithubEventsLambda.java
- src/test/java/org/opensearchmetrics/lambda/GithubEventsLambdaTest.java
Eventbridge rule calls the lambda function at the end of the day, so by changing the default to indexing yesterday AND today's events, we can get the most recent data for the maintainer dashboard.
Part of https://github.com/opensearch-project/opensearch-metrics/issues/76 
> Changed s3 event index lambda to default index yesterday and today

- build.gradle
Upgraded opensearch-high-level-rest-client to 2.18.0
Part of https://github.com/opensearch-project/opensearch-metrics/issues/80
> Upgraded opensearch-high-level-rest-client to 2.18.0

- DEVELOPER_GUIDE.md
- README.md
- build.gradle
- infrastructure/lib/constructs/automationAppSns.ts
- infrastructure/lib/enums/project.ts
- infrastructure/lib/infrastructure-stack.ts
- infrastructure/lib/stacks/eventCanaryWorkflow.ts
- infrastructure/lib/stacks/gitHubAutomationApp.ts
- infrastructure/lib/stacks/monitoringDashboard.ts
- infrastructure/test/event-canary-workflow-stack.test.ts
- infrastructure/test/monitoring-stack.test.ts
- src/main/java/org/opensearchmetrics/datasource/DataSourceType.java
- src/main/java/org/opensearchmetrics/github/GhAppClient.java
- src/main/java/org/opensearchmetrics/lambda/EventCanaryLambda.java
- src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
- src/main/java/org/opensearchmetrics/model/github/GhAppAccessToken.java
- src/main/java/org/opensearchmetrics/util/SecretsManagerUtil.java
- src/test/java/org/opensearchmetrics/github/GhAppClientTest.java
- src/test/java/org/opensearchmetrics/lambda/EventCanaryLambdaTest.java
- src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java
- src/test/java/org/opensearchmetrics/util/SecretsManagerUtilTest.java
1. Adds a lambda(EventCanaryLambda) that will create/delete a label every 10 minutes
2. Adds an alarm for the LabelCanary metric that will trigger on missing data.
3. Closes and sets branch for 2.19 release
https://github.com/opensearch-project/opensearch-metrics/issues/105
> Docker s3 data lake app monitoring

- src/main/java/org/opensearchmetrics/lambda/GithubEventsLambda.java
- src/main/java/org/opensearchmetrics/metrics/MetricsCalculation.java
- src/main/java/org/opensearchmetrics/util/OpenSearchUtil.java
- src/test/java/org/opensearchmetrics/lambda/GithubEventsLambdaTest.java
- src/test/java/org/opensearchmetrics/metrics/MetricsCalculationTest.java
- src/test/java/org/opensearchmetrics/util/OpenSearchUtilTest.java
Add alias to index if requested , onboarded alias creation for maintainer-activity indices.
https://github.com/opensearch-project/opensearch-metrics/issues/120
Pending test
> Support mapping alias for maintainer-activity indices

- src/main/java/org/opensearchmetrics/metrics/MetricsCalculation.java
- src/main/java/org/opensearchmetrics/metrics/release/ReleaseRepoFetcher.java
- src/test/java/org/opensearchmetrics/metrics/release/ReleaseMetricsTest.java
- src/test/java/org/opensearchmetrics/metrics/release/ReleaseRepoFetcherTest.java
The current set up has below mapping:
```
<repository_name> : <component_name>
```
This causes an issue with multi-component repositories such as notifications and notifications core. 
We want to track per component rather than per repo. This PR switches the mapping to below:
```
<component_name>: <repository_name>
```
https://github.com/opensearch-project/opensearch-build-libraries/issues/643
resolves https://github.com/opensearch-project/opensearch-metrics/issues/129
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificat …
> Switch values for components repo map

- src/main/java/org/opensearchmetrics/metrics/MetricsCalculation.java
Lamda throws an error that document already exists since the repo name is same. This PR fixes the documentID to componentName suffix.
> Switch document ID from repo name to unique component name

- .github/CODEOWNERS
- MAINTAINERS.md
- Adding @gaiksaya as maintainer.
- Moving @bshien Emeritus section.
https://github.com/opensearch-project/.github/issues/331
> Update maintainers for the repo

- infrastructure/lib/stacks/gitHubAutomationApp.ts
- src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
- src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java
Update release tracker and automation app version
Coming from https://github.com/opensearch-project/opensearch-build/pull/5534
> Update release tracker and automation app version

- src/main/java/org/opensearchmetrics/metrics/release/ReleaseInputs.java
- src/test/java/org/opensearchmetrics/metrics/release/ReleaseInputsTest.java
Adds 3.2 version for tracking and closes 2.19.3
https://github.com/opensearch-project/opensearch-build/issues/5595
> Adds 3.2 version for tracking and closes 2.19.3
